name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  php-checks:
    name: php checks
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
        with:
          php-version: 7.4
          extensions: mbstring

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          echo "::add-matcher::.github/matchers/phplint.json"
          composer install --prefer-dist --no-progress

      - name: Run checks
        run: |
          echo "::add-matcher::.github/matchers/phpcs.json"
          echo "::add-matcher::.github/matchers/phpunit.json"

          export PHPLINT_FLAGS="--no-progress"
          export PHPCS_FLAGS="--report=csv -q"
          export PHPSTAN_FLAGS="--no-progress"

          composer check

          echo "::remove-matcher owner=phpunit::"
          echo "::remove-matcher owner=phpcs::"
          echo "::remove-matcher owner=phplint::"
